#
# Our adjustments to rubocop default code policies.
#
# See http://rubocop.readthedocs.io/en/latest/ for detailed configuration options documentation

# Additional cops for working with RSpec. See https://github.com/backus/rubocop-rspec
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake


AllCops:
  Exclude:
    - 'tmp/**/*.rb'
    # See https://qiita.com/ozhaan/items/40ea864757162e931be1
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5.0

Metrics/BlockLength:
  Exclude:
    # The default guard-rspec config fails this, but it's ok.
    - 'Guardfile'
    - 'spec/**/*_spec.rb'
    - '*.gemspec'

Naming/FileName:
  Exclude:
    - lib/bundler-toolbox.rb

# Big screens are common :)
Layout/LineLength:
  Max: 120

# We use RSpec as a format linter, so no specific classes under test neccessarily :)
RSpec/DescribeClass:
  Enabled: false

# Prefer to use the up-front message expectations
RSpec/MessageSpies:
  Enabled: false

# Prefer structure over small indentation
RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

# Prefer to create "real" booleans using double negation
Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# I actually use this a lot with `private :foo=`
Style/AccessModifierDeclarations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Opt-ins to post-0.80 cops
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
