name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '2.7'

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-gems-${{matrix.ruby}}
        restore-keys: |
          ${{ runner.os }}-gems-${{matrix.ruby}}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{matrix.ruby}}"
    - name: Install dependencies and run rubocop
      env:
        # Neccessary for jruby test coverage
        JRUBY_OPTS: "--debug"
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - head
        - '2.7'
        - '2.6'
        - '2.5'
        - jruby
        - jruby-head

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-gems-${{matrix.ruby}}
        restore-keys: |
          ${{ runner.os }}-gems-${{matrix.ruby}}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{matrix.ruby}}"
    - name: Install dependencies and run RSpec
      env:
        # Neccessary for jruby test coverage
        JRUBY_OPTS: "--debug"
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        bundle exec rspec

    - uses: actions/upload-artifact@v2
      with:
        name: "Test Coverage ${{matrix.ruby}}"
        path: coverage/

  cucumber:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - head
        - '2.7'
        - '2.6'
        - '2.5'
        - jruby
        - jruby-head

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-gems-${{matrix.ruby}}
        restore-keys: |
          ${{ runner.os }}-gems-${{matrix.ruby}}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{matrix.ruby}}"
    - name: Install dependencies and run RSpec
      env:
        # Neccessary for jruby test coverage
        JRUBY_OPTS: "--debug"
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        bundle exec cucumber features
